### ISSUE TITLE
Urgent Website Update Needed

### ISSUE THREAD

**Issue by kborchers** [jquery/content#11] opened 2016-03-29 22:00 UTC
Due to an error in Scott's gilded-wordpress package, the core and mobile API sites have not been publishing since December. I tracked down the issue and sent PRs to https://github.com/scottgonzalez/gilded-wordpress/ and https://github.com/scottgonzalez/grunt-wordpress/ which have been merged and released.

It would be great if someone could update https://github.com/jquery/jquery-wp-content to use gilded-wordpress@1.0.3 similar to this update https://github.com/jquery/jquery-wp-content/commit/101f563868b9d31351487b790e32c35ecc769ec4 and push to master but don't tag a release until the next step is complete.

Next, every one of our websites will need to be upgraded to grunt-jquery-content@3.0.1 similar to this update https://github.com/jquery/api.jquery.com/commit/aab36ba0238c3c6f48ffcbc164da2789ccb55e3f Making all of these changes should deploy to stage and all sites should work, including the broken API sites.

If all sites properly deploy to stage, tag the release for jquery-wp-content and then tag a release for every site and we should be back in business. Please ping this issue if you intend to work on this so we don't get multiple people stepping on each other. Also, if you don't have access to do any of this, feel free to stand it all up as PRs with clear messaging that no one should merge as we need to do everything at once to avoid sites getting left behind and being unable to deploy. Also, any question just add them to this issue. Thanks!

**Comment by arschmitz** [comment] 2016-03-29 22:17
a caution on this stage is no longer "really" staging. Staging uses an ansible server while the live site is still using puppet. We had trouble with this when last deploying UI

**Comment by aulvi** [comment] 2016-03-29 23:13
@kborchers (and anyone else working on this)  I'm around, so ping me if you need a hand or just an extra set of eyes.

**Comment by agcolom** [comment] 2016-03-30 14:33
Just letting everyone know that I'm working on this now. It's kind of slow as I am testing every site before sending the PR, and I'm not super fast ;-) (and I have kids around as well as I am on holiday, so taking it one step at a time :-) )

**Comment by agcolom** [comment] 2016-03-30 15:11
Taking a break. So far, completed all api sites, jquery.org and jquery.com 
Will continue this evening after dinner (in about 2-3 h).

**Comment by agcolom** [comment] 2016-03-30 18:58
I'm having problems deploying codeorigin.jquery.com locally. 
This is the error I am getting: 
Running "wordpress-validate" task
Verifying XML-RPC version...
Warning: Unknown error. Please ensure that your database server is running and WordPress is functioning properly. Use --force to continue.

So I'm leaving this one out for now. I don't know whether this site should be deployed differently. Also the config.json file appears to be different from the other sites... Any help/hint would be greatly appreciated.

**Comment by dmethvin** [comment] 2016-03-30 19:34
Yes, codeorigin is different so it may not need this. Can somone confirm?

**Comment by aulvi** [comment] 2016-03-30 19:47
codeorigin.jquery.com is still managed via puppet, just like the other two wordpress servers. I would expect the deployment to work the same. @gnarf what am I missing?

**Comment by gnarf** [comment] 2016-03-30 19:48
pretty sure it should work the same...

**Comment by aulvi** [comment] 2016-03-30 19:55
@agcolom The xml-rpc errors are pretty common and normally boil down to some form of "cannot reach server". I've seen them when servers are legitimately down, when my hosts file is pointing into space, and also when the SSL certificates on the target server have expired. I mean, it could be anything.

Feel free to ping me on Hangouts if you want to pair up and debug.

**Comment by agcolom** [comment] 2016-03-31 09:11
@aulvi Thanks. The error I'm getting totally matches what you're saying as when I try to connect to the local url I get "Error establishing a database connection" while all the other servers work! Very strange! So the only thing I can think of is that my config file is wrong... I'll try to catch you this evening UK time if I can't find the solution by then :-)

**Comment by aulvi** [comment] 2016-03-31 21:04
Update: Anne and I reviewed her configuration and resolved an `npm install` error by upgrading her node and npm versions. However, we cannot deploy 'codeorigin' to her local MAMP install, it continues to fail. Additionally, the site `http://local.codeorigin.jquery.com` returns a database error, so clearly something in WP isn't happy.

I am working to reproduce this error locally in hopes of arriving at a fix. If anyone has feedback or suggestions on how to fix, please let us know.

Thanks everyone!

**Comment by gnarf** [comment] 2016-03-31 21:21
I remember running into a similar problem on one of the live sites, and we
had to delete a site from the wordpress database.

It might be a good idea to try to backup the DB on your local (in case this
doesn't work) and then blow up the whole database and recreate it.

**Comment by gnarf** [comment] 2016-03-31 21:21
cc @scottgonzalez I think "Database Error" was all we got when we were
trying to debug api.jqueryui.com/1.10 right?

**Comment by scottgonzalez** [comment] 2016-04-01 20:10
Deleting the database would certainly give her a fresh start, which would resolve the issue if there's a mismatch between site IDs, but I don't think that's what's happening. If it were, she'd be able to connect to the database, but would have issues pulling up the site configuration. I guess it depends on what specific database error she's getting.

**Comment by scottgonzalez** [comment] 2016-04-01 20:12
I'll also note that deleting the database is not a concern (i.e., you don't need a backup because it's not the source of truth for any information). Walking through the install screen and site deploys will give you a full restore of the database.

**Comment by gnarf** [comment] 2016-04-01 20:22
Scott I seem to remember there was some generic `echo "Database Error";
exit();` going on inside our sunrise when it connected to the DB fine and
had problems setting the site configuration correctly

**Comment by scottgonzalez** [comment] 2016-04-01 20:39
Nah, that'd be something like "Things are horribly broken. Find nacin."

**Comment by agcolom** [comment] 2016-04-01 20:44
I have some more info, if that helps. If in config.json if I use the url local.codeorigin.jquery.com, the deploy fails on Running "wordpress-validate" task 
**However**, if I use a different url, such as local.api.jquery.com, **that step works**, and the fail is on the following task 
Running "wordpress-sync" task
Synchronizing terms...
Getting taxonomies from WordPress...
Got taxonomies from WordPress.
Getting category terms...
Got category terms.
Getting post_tag terms...
Got post_tag terms.
Getting post_format terms...
Got post_format terms.
Publishing terms...
Published all terms.
Deleting old terms...
Deleting category ajax...
Warning: XML-RPC fault: Sorry, deleting the term failed. Use --force to continue.

**Comment by agcolom** [comment] 2016-04-01 20:48
BTW, I'm just thinking, since all the sites have been updated either in production or on stage, should we close this issue? Or should we wait until we have all sites deployed to production?

**Comment by scottgonzalez** [comment] 2016-04-01 21:00
@agcolom You cannot debug this using grunt. The problem is inside WordPress.

**Comment by aulvi** [comment] 2016-04-02 04:14
@agcolom Yes, I think this Issue is satisfied and can be closed. However, we should probably have another Issue opened for testing codeorigin locally.

**Comment by agcolom** [comment] 2016-04-02 12:52
Closing this issue as resolved and opening a new one for the local testing. I will to this issue for the details of the discussion. I will carry out a few tests now first.

**Closed as completed by agcolom** 2016-04-02 12:52 UTC
